export default [
  {
    name: 'ALAN',
    slug: 'alan',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // location: '',
    // capacity: 123,
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
    // memberSince: 2017,
  },
  {
    name: 'altLAN',
    slug: 'altlan',
    tagline: `altLAN, part of altGaming, is a celebration of gaming culture.`,
    website: 'https://altlan.co.uk/altlan',
    favicon: '/altlan.png',
    location: 'Stourbridge, West Midlands',
    // capacity: 123,
    social: {
      discord: 'https://discord.gg/jvgX8r7',
      facebook: 'https://facebook.com/altlanuk',
      twitter: 'altgaminguk',
    },
    memberSince: 2017,
  },
  {
    name: 'BreachLAN',
    slug: 'breachlan',
    tagline: `Aberdeen's Premier 72hr LAN Party.`,
    website: 'https://www.breachlan.party/',
    favicon: '/breachlan.ico',
    location: 'Aberdeen, Scotland',
    capacity: 20,
    social: {
      discord: 'https://discord.breachlan.party/',
      facebook: 'breachlan',
      instagram: 'breachlan',
      youtube: '@BreachLAN',
    },
    memberSince: 2017,
  },
  {
    name: 'Continuum',
    slug: 'continuum',
    tagline: `Causing problems on the internet since 2018. Now with added LANs and pizza.`,
    website: 'https://continuumgaming.co.uk/',
    favicon: '/continuum.svg',
    location: 'Padworth, Berkshire',
    capacity: 35,
    social: {
      discord: 'https://discord.gg/5Ej2KPpSYE',
      facebook: 'profile.php?id=100090937340886',
      instagram: 'continuumgaming_',
    },
    memberSince: 2023,
  },
  {
    name: 'Enclave',
    slug: 'enclave',
    tagline: `A large community driven celebration of LAN gaming across five days in the heart of the UK.`,
    website: 'https://www.enclavelan.com/',
    favicon: '/enclavelan.png',
    location: 'Marshall Arena at Stadium MK, Milton Keynes',
    capacity: 1080,
    social: {
      discord: 'https://discord.gg/ekWqVjjKWD',
      facebook: 'EnclaveLAN',
      instagram: 'enclave_lan',
      twitter: 'EnclaveLan',
      youtube: '@Enclave_LAN',
    },
    memberSince: 2025,
  },
  {
    name: 'EntropyLAN',
    slug: 'entropy',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // location: '',
    // capacity: 123,
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   reddit: 'subreddit',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
    // memberSince: 2017,
  },
  {
    name: 'EPIC.LAN',
    slug: 'epiclan',
    tagline: `A large community LAN party featuring a great range of fun tournaments, casual games and esports tournaments.`,
    website: 'https://epiclan.co.uk',
    favicon: '/epiclan.png',
    location: 'Kettering Leisure Village, Northamptonshire',
    capacity: 700,
    social: {
      discord: 'https://discord.gg/epiclan',
      facebook: 'epiclan',
      // instagram: 'username',
      // reddit: 'subreddit',
      twitter: 'epiclan',
      // youtube: '@username',
    },
    memberSince: 2014,
  },
  {
    name: 'Frag-O-Matic',
    slug: 'fragomatic',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // location: '',
    // capacity: 123,
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   reddit: 'subreddit',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
    // memberSince: 2017,
  },
  {
    name: 'FragSoc',
    slug: 'fragsoc',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // location: '',
    // capacity: 123,
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   reddit: 'subreddit',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
    // memberSince: 2017,
  },
  {
    name: 'Gaming Scotland',
    slug: 'gamingscotland',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // capacity: 123,
    // location: '',
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   reddit: 'subreddit',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
    // memberSince: 2017,
  },
  {
    name: 'Gamers Unite LAN',
    slug: 'gul',
    tagline: `A community first LAN event. Single day, 4 times a year.`,
    website: 'https://www.gamersunitelan.com/',
    favicon: '/gul.png',
    location: 'Swindon, Wiltshire',
    capacity: 40,
    social: {
      discord: 'https://discord.gg/2akPpZD73v',
      facebook: 'Gamers-Unite-LAN',
      instagram: 'gamersunitelan',
      reddit: 'GamersUniteLAN',
      twitter: 'GamersUniteLAN',
      youtube: '@GamersUnite923',
    },
    // memberSince: 2017,
  },
  {
    name: 'GGHQ',
    slug: 'gghq',
    tagline: `Gloucestershire based Gaming Community`,
    website: 'https://gghq.io/',
    favicon: '/gghq.png',
    location: 'Cheltenham, Gloucestershire',
    capacity: 20,
    social: {
      discord: 'https://discord.gg/zeW4Rs4rDe',
      // facebook: 'username',
      instagram: 'gghq_io',
      reddit: 'gghqio',
      // twitter: 'username',
      youtube: '@gghqio',
    },
    // memberSince: 2017,
  },
  {
    name: 'HodgLAN',
    slug: 'hodglan',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // location: '',
    // capacity: 123,
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   reddit: 'subreddit',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
    // memberSince: 2017,
  },
  {
    name: 'LANOps',
    slug: 'lanops',
    // tagline: ``,
    website: 'https://lanops.co.uk/',
    favicon: '/lanops.png',
    location: 'Barnsley, South Yorkshire',
    capacity: 70,
    social: {
      discord: 'https://discord.gg/JjeFunevpc',
      facebook: 'https://www.facebook.com/LanOps',
      // instagram: 'username',
      // reddit: 'subreddit',
      // twitter: 'username',
      // youtube: '@username',
    },
    // memberSince: 2017,
  },
  {
    name: 'LlamaLAN',
    slug: 'llama',
    // tagline: ``,
    website: 'https://www.llamalan.co.uk/',
    favicon: '/llamalan.jpg',
    location: 'Chatham, Kent',
    // capacity: 123,
    social: {
      discord: 'https://discord.breachlan.party/',
      facebook: 'https://www.facebook.com/#!/group.php?gid=4079644074'
      // instagram: 'username',
      // reddit: 'subreddit',
      // twitter: 'username',
      // youtube: '@username',
    },
    // memberSince: 2017,
  },
  {
    name: 'MiniLAN',
    slug: 'minilan',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // location: '',
    // capacity: 123,
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   reddit: 'subreddit',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
    // memberSince: 2017,
  },
  {
    name: 'P-LAN',
    slug: 'plan',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // memberSince: 2017,
    // location: '',
    // capacity: 123,
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   reddit: 'subreddit',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
  },
  {
    name: 'ShinyLAN',
    slug: 'shinylan',
    tagline: `ShinyLAN is a well established LAN party with its roots going back over 25 years based in the South West of the UK.`,
    website: 'http://www.shinylan.co.uk/',
    favicon: '/shinylan.ico',
    location: 'Cerne Abbas, Dorchester',
    social: {
      // discord: 'https://discord.gg/#',
      facebook: 'https://www.facebook.com/shinylanuk/',
      // instagram: 'username',
      // reddit: 'subreddit',
      twitter: 'https://twitter.com/ShinyLAN/',
      // youtube: '@username',
    },
  },
  {
    name: 'StratLAN',
    slug: 'stratlan',
    tagline: `More than just an event StratLAN is a community, a place to play together, meet like minded gamers and spend the occasional weekend away from your troubles. We support each other, enjoy each other and accept each other.`,
    website: 'https://stratlan.com/',
    favicon: '/stratlan.png',
    location: 'Stratford-upon-Avon Racecourse, Stratford-Upon-Avon',
    capacity: 250,
    social: {
      discord: 'https://stratlan.com/',
      facebook: 'https://www.facebook.com/Stratlan',
      // instagram: 'username',
      // reddit: 'subreddit',
      twitter: 'Strat_LAN',
      // youtube: '@username',
    },
    memberSince: 2014,
  },
  {
    name: 'the BIG GAME',
    slug: 'tbg',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // location: '',
    // capacity: 123,
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   reddit: 'subreddit',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
    // memberSince: 2017,
  },
  {
    name: 'Zero Ping Heroes',
    slug: 'zeroping',
    tagline: `An exceptional LAN and a collection of shared gaming experiences in a friendly social atmosphere.`,
    website: 'https://zeropingheroes.co.uk/',
    favicon: '/zph.png',
    location: 'Lewes, East Sussex',
    // capacity: 123,
    social: {
      discord: 'https://discord.com/invite/KabHQJUc',
      // facebook: 'username',
      // instagram: 'username',
      // reddit: 'subreddit',
      // twitter: 'username',
      // youtube: '@username',
    },
    // memberSince: 2017,
  },
].sort((a, b) => a.name.localeCompare(b.name))
