export default [
  {
    name: 'ALAN',
    slug: 'alan',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // location: '',
    // capacity: 123,
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
    // memberSince: 2017,
  },
  {
    name: 'altLAN',
    slug: 'altlan',
    tagline: `altLAN, part of altGaming, is a celebration of gaming culture.`,
    website: 'https://altlan.co.uk/altlan',
    favicon: '/altlan.png',
    location: 'Stourbridge, West Midlands',
    // capacity: 123,
    social: {
      discord: 'https://discord.gg/jvgX8r7',
      facebook: 'https://facebook.com/altlanuk',
      twitter: 'altgaminguk',
    },
    memberSince: 2017,
  },
  {
    name: 'BreachLAN',
    slug: 'breachlan',
    tagline: `Aberdeen's Premier 72hr LAN Party.`,
    website: 'https://www.breachlan.party/',
    favicon: '/breachlan.ico',
    location: 'Aberdeen, Scotland',
    capacity: 20,
    social: {
      discord: 'https://discord.breachlan.party/',
      facebook: 'breachlan',
      instagram: 'breachlan',
      youtube: '@BreachLAN',
    },
    memberSince: 2017,
  },
  {
    name: 'Continuum',
    slug: 'continuum',
    tagline: `Causing problems on the internet since 2018. Now with added LANs and pizza.`,
    website: 'https://continuumgaming.co.uk/',
    favicon: '/continuum.svg',
    location: 'Padworth, Berkshire',
    capacity: 35,
    social: {
      discord: 'https://discord.gg/5Ej2KPpSYE',
      facebook: 'profile.php?id=100090937340886',
      instagram: 'continuumgaming_',
    },
    memberSince: 2023,
  },
  {
    name: 'Enclave',
    slug: 'enclave',
    tagline: `A large community driven celebration of LAN gaming across five days in the heart of the UK.`,
    website: 'https://www.enclavelan.com/',
    favicon: '/enclavelan.png',
    location: 'Marshall Arena at Stadium MK, Milton Keynes',
    capacity: 1080,
    social: {
      discord: 'https://discord.gg/ekWqVjjKWD',
      facebook: 'EnclaveLAN',
      instagram: 'enclave_lan',
      twitter: 'EnclaveLan',
      youtube: '@Enclave_LAN',
    },
    memberSince: 2025,
  },
  {
    name: 'EntropyLAN',
    slug: 'entropy',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // location: '',
    // capacity: 123,
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   reddit: 'subreddit',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
    // memberSince: 2017,
  },
  {
    name: 'EPIC.LAN',
    slug: 'epiclan',
    tagline: `A large community LAN party featuring a great range of fun tournaments, casual games and esports tournaments.`,
    website: 'https://epiclan.co.uk',
    favicon: '/epiclan.png',
    location: 'Kettering Leisure Village, Northamptonshire',
    capacity: 700,
    social: {
      discord: 'https://discord.gg/epiclan',
      facebook: 'epiclan',
      instagram: 'epiclan',
      twitter: 'epiclan',
      youtube: '@epiclanuk',
    },
    memberSince: 2014,
  },
  {
    name: 'Frag-O-Matic',
    slug: 'fragomatic',
    tagline: `Frag-o-Matic is a gaming festival that offers an alternative to the popular LAN-parties.`,
    website: 'https://www.fom.be/',
    favicon: '/fom.png',
    location: 'Wieze, Belgium',
    capacity: 1000,
    social: {
      discord: 'https://discord.gg/8SfUy36',
      facebook: 'fomlan',
      instagram: 'fomlanbe',
      twitter: 'FoMLan',
      youtube: '@FOMetv',
    },
    memberSince: 2022,
  },
  {
    name: 'FragSoc',
    slug: 'fragsoc',
    tagline: `FragSoc is the University of York's Video Gaming and LAN society as part of the University of York Student Union`,
    website: 'https://fragsoc.co.uk/',
    favicon: '/fragsoc.png',
    location: 'University of York, Yorkshire',
    capacity: 100,
    social: {
      discord: 'https://discord.gg/vaTV73U5Hz',
      facebook: 'groups/FragSoc',
      instagram: 'FragSoc',
      twitter: 'FragSoc',
      youtube: '@FragSoc',
    },
    memberSince: 2018,
  },
  {
    name: 'Gaming Scotland',
    slug: 'gamingscotland',
    tagline: `Gaming Scotland is one of Scotlands oldest and most notable LAN party events based in Central Scotland along with a large online community.`,
    website: 'https://web.archive.org/web/20240622093405/https://www.gamingscotland.com/',
    favicon: '/gamingscotland.png',
    capacity: 100,
    location: 'Larbert, Falkirk',
    social: {
      discord: 'https://discord.gg/9AdRK3qztQ',
      facebook: 'gamingscotland',
      instagram: 'langamingscotland',
      twitter: 'gamingscotland',
      youtube: '@GamingScotland',
    },
    memberSince: 2019,
  },
  {
    name: 'Gamers Unite LAN',
    slug: 'gul',
    tagline: `A community first LAN event. Single day, 4 times a year.`,
    website: 'https://www.gamersunitelan.com/',
    favicon: '/gul.png',
    location: 'Swindon, Wiltshire',
    capacity: 40,
    social: {
      discord: 'https://discord.gg/2akPpZD73v',
      facebook: 'Gamers-Unite-LAN',
      instagram: 'gamersunitelan',
      reddit: 'GamersUniteLAN',
      twitter: 'GamersUniteLAN',
      youtube: '@GamersUnite923',
    },
    memberSince: 2024,
  },
  {
    name: 'GGHQ',
    slug: 'gghq',
    tagline: `Gloucestershire based Gaming Community`,
    website: 'https://gghq.io/',
    favicon: '/gghq.png',
    location: 'Cheltenham, Gloucestershire',
    capacity: 20,
    social: {
      discord: 'https://discord.gg/zeW4Rs4rDe',
      facebook: 'groups/gghq.io',
      instagram: 'gghq_io',
      reddit: 'gghqio',
      twitter: 'gghqio',
      youtube: '@gghqio',
    },
    memberSince: 2018,
  },
  {
    name: 'HodgLAN',
    slug: 'hodglan',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // location: '',
    // capacity: 123,
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   reddit: 'subreddit',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
    // memberSince: 2017,
  },
  {
    name: 'LANOps',
    slug: 'lanops',
    tagline: `LanOps is a non-profit community run by volunteers with one goal: have fun and be awesome.`,
    website: 'https://lanops.co.uk/',
    favicon: '/lanops.png',
    location: 'Barnsley, South Yorkshire',
    capacity: 70,
    social: {
      discord: 'https://discord.gg/JjeFunevpc',
      facebook: 'https://www.facebook.com/LanOps',
      instagram: 'lanops.uk',
      youtube: '@LanOps',
    },
    memberSince: 2017,
  },
  {
    name: 'LlamaLAN',
    slug: 'llama',
    tagline: `Providing LANs for llamas since 2002.`,
    website: 'https://www.llamalan.co.uk/',
    favicon: '/llamalan.png',
    location: 'Chatham, Kent',
    capacity: 40,
    social: {
      discord: 'https://discord.breachlan.party/',
      facebook: 'llamalanuk',
      twitter: 'LlamaLANUK',
    },
    memberSince: 2017,
  },
  {
    name: 'MiniLAN',
    slug: 'minilan',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // location: '',
    // capacity: 123,
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   reddit: 'subreddit',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
    // memberSince: 2017,
  },
  {
    name: 'P-LAN',
    slug: 'plan',
    // tagline: ``,
    // website: 'https://www.example.com/',
    // favicon: '/example.png',
    // memberSince: 2017,
    // location: '',
    // capacity: 123,
    // social: {
    //   discord: 'https://discord.gg/#',
    //   facebook: 'username',
    //   instagram: 'username',
    //   reddit: 'subreddit',
    //   twitter: 'username',
    //   youtube: '@username',
    //},
  },
  {
    name: 'ShinyLAN',
    slug: 'shinylan',
    tagline: `ShinyLAN is a well established LAN party with its roots going back over 25 years based in the South West of the UK.`,
    website: 'http://www.shinylan.co.uk/',
    favicon: '/shinylan.ico',
    location: 'Cerne Abbas, Dorchester',
    social: {
      discord: 'https://discord.gg/gkTjvXHWgG',
      facebook: 'shinylanuk',
      instagram: 'shinylanuk',
      twitter: 'https://twitter.com/ShinyLAN/',
    },
  },
  {
    name: 'StratLAN',
    slug: 'stratlan',
    tagline: `More than just an event StratLAN is a community, a place to play together, meet like minded gamers and spend the occasional weekend away from your troubles. We support each other, enjoy each other and accept each other.`,
    website: 'https://stratlan.com/',
    favicon: '/stratlan.png',
    location: 'Stratford-upon-Avon Racecourse, Stratford-Upon-Avon',
    capacity: 250,
    social: {
      discord: 'https://stratlan.com/',
      facebook: 'https://www.facebook.com/Stratlan',
      // instagram: 'username',
      // reddit: 'subreddit',
      twitter: 'Strat_LAN',
      // youtube: '@username',
    },
    memberSince: 2014,
  },
  {
    name: 'the BIG GAME',
    slug: 'tbg',
    tagline: `The BIG GAME is a UK LAN party based in Southampton, Hampshire - started in 2000 by putty_thing (our fearless leader).`,
    website: 'https://thebiggame.org/',
    favicon: '/tbg.png',
    location: 'Southampton, Hampshire',
    capacity: 70,
    social: {
      discord: 'https://discord.gg/GP44GXq',
      facebook: 'tbglan',
      instagram: 'tbglan',
      youtube: '@ThebiggameOrg',
    },
    memberSince: 2017,
  },
  {
    name: 'Zero Ping Heroes',
    slug: 'zph',
    tagline: `A celebration of shared game experiences where together we cultivate a friendly social atmosphere for game-lovers of all backgrounds and skill levels.`,
    website: 'https://zeropingheroes.co.uk/',
    favicon: '/zph.png',
    location: 'Lewes, East Sussex',
    capacity: 30,
    social: {
      discord: 'https://zph.in/discord',
      facebook: 'zeropingheroes',
      instagram: 'zeropingheroes',
      twitter: 'zeropingheroes',
    },
    memberSince: 2017,
  },
].sort((a, b) => a.name.localeCompare(b.name))
